name: sequence
description: sequence
version: 1.0.0
publish_to: https://dart.cloudsmith.io/nyx/dart_utilities/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1
  dart_extensions:
    hosted: https://dart.cloudsmith.io/nyx/dart_utilities/
    version: ^1.0.0